### ISSUE TITLE
Dynamically redraw the chart when data changes

### ISSUE THREAD

**Issue by ruchisinghal** [FERNman/angular-google-charts#39] opened 2018-11-27 03:43 UTC
Hi

I am getting the values of [data] from an API. It renders fine in the first time. But when these values change, the chart does not redraw though [data] has updated. but the graph does not re render itself.

**Comment by FERNman** [comment] 2018-11-27 12:08
Hi @ruchisinghal ,

could you provide me with some code?

**Comment by yoadster** [comment] 2018-12-04 17:21
This is happening for me also. Would be grateful to know the resolution.

**Comment by FERNman** [comment] 2018-12-05 09:48
I just looked into it and now understand where the problem's coming from. The `GoogleChartComponent` itself doesn't implement the `ngDoCheck` method, that means it can't detect changes inside the input properties as long as the references don't change.

What you have to do to make it work (for now) is to assign a new object instead of changing the old one. I'll look into that and, if it doesn't affect performance too much, will implement it.

Working example: 

```typescript
// Data was already initialized, this is the method where the data gets updated
// This method sets the chartData object to a new reference and triggers ngOnChanges
updateChartData(newData: Array<Array<string | int>>) {
  chartData = newData;
}
```

(Currently) not working example:

```typescript
// Data was already initialized, this is the method where the data gets updated
// This method doesn't change the chartData reference and therefore doesn't trigger ngOnChanges
updateChartData(newValues: Array<int>) {
   for (let i = 0; i < newValues.size(); i++) {
    chartData[i][1] = newValues[i];
  }
}
```

**Comment by joannaz** [comment] 2019-03-01 01:07
Hey! I bumped into this issue today. An easy quick fix is to simply write
` this.chartData = Object.assign([], this.chartData) ` to reassign to the exposed dataset property into your component so it triggers change detection. 

More information from this issue in a different library:
https://github.com/valor-software/ng2-charts/issues/959#issuecomment-367171535

Hope this helps weary travellers :)

**Comment by FERNman** [comment] 2019-03-01 08:21
I think I'll close this for now, as both fixes mentioned are pretty easy, whereas checking whether a property in the `chartData` object changed isn't that easy. If anyone has an idea on how to implement `ngDoCheck` for the `chartData` object, feel free to point it out and I'll implement it (or even better, just create a pull request).

**Closed by FERNman** 2019-03-01 08:21 UTC
Labels: bug, wontfix

**Comment by samsamm777** [comment] 2020-01-29 17:24
None of these solutions work for me. The chart disappears once you change a value. No errors at all.

**Comment by virendrapatel62** [comment] 2020-04-16 02:06
> o errors at a

yes

**Comment by erdemmalliq** [comment] 2020-05-16 22:57
Chart is updating itself when data is changed with Object.assign. But now the selected point is disappearing. How can I make a point get selected again?

Example:
this.chart.getChart().setSelection([{row: 0}]);

**Comment by m1niml** [comment] 2020-06-03 14:26
None of these solutions works with Angular-CLI. I am trying to change the chartType from one to another but the changes won't reflect until I either a) filter the data b) resize the window

**Comment by m1niml** [comment] 2020-06-03 14:27
No way to call chart.draw either

**Comment by m1niml** [comment] 2020-06-03 15:20
Something else odd to note. When I print the chart object to the console, it has 2 type properties

{title: "Counts By Employee", **type: "PieChart"**, columns: Array(2), data: Array(2), options: {…}, …}
columns: (2) ["Employee", "Index Count"]
data: (2) [Array(2), Array(2)]
filters: (2) [{…}, {…}]
options: {is3D: true}
title: "Counts By Employee"
**type: "Table"**
__proto__: Object

**Comment by m1niml** [comment] 2020-06-03 15:21
I guess since this issue is closed and no new responses, I will need to open a new issue

**Comment by FERNman** [comment] 2020-06-12 12:39
@m1niml I guess what you are experiencing is not 100% the same as this issue. If you didn't yet manage to fix the issue, feel free to open up a new one (and please provide a simple reproduction).
