### ISSUE TITLE
When I switch to other tab and come back graph disappears, old issue reappear in version 0.1.6

### ISSUE THREAD

**Issue by ShitalD** [FERNman/angular-google-charts#79] opened 2019-07-03 06:22 UTC
Using version 0.1.6, I have my graph in a tab, when I switch to other tab and come back graph disappears. Getting below error stack when reloading tab. It seems this.doneLoading is true when we reload but it doesn't work. I reverted to version 0.1.3 from 0.1.6 and the issue is solved, so it seems its broken after that version. Also observed in version 0.1.6 the number labels on Y axis are appearing on alternate lines only.
ChartComponent.html:11 ERROR TypeError: Object(...) is not a function
    at ScriptLoaderService.get [as onReady] (angular-google-charts.js?0889:34)
    at GoogleChartComponent.ngOnInit (angular-google-charts.js?0889:513)
    at checkAndUpdateDirectiveInline (core.js?593e:12401)
    at checkAndUpdateNodeInline (core.js?593e:13928)
    at checkAndUpdateNode (core.js?593e:13871)
    at debugCheckAndUpdateNode (core.js?593e:14764)
    at debugCheckDirectivesFn (core.js?593e:14705)
    at Object.eval [as updateDirectives] (ChartComponent.html:11)
    at Object.debugUpdateDirectives [as updateDirectives] (core.js?593e:14690)
    at checkAndUpdateView (core.js?593e:13837)

**Comment by mgharish** [comment] 2019-07-05 04:46
Even I have the same issue

**Comment by FERNman** [comment] 2019-08-04 16:44
What do you mean by switch tab? Like switching tabs in the browser or some custom tabs in your website?

**Comment by mgharish** [comment] 2019-08-09 06:37
Going to some other component and coming back

**Comment by FERNman** [comment] 2019-11-24 16:38
I don't think this is actually a valid issue, or at least I was not able to reproduce it. I will close this for now, but if anybody else experiences this problem, feel free to comment here.

**Closed by FERNman** 2019-11-24 16:38 UTC
