### ISSUE TITLE
How do I use map?

### ISSUE THREAD

**Issue by AndreHermanto** [FERNman/angular-google-charts#183] opened 2020-11-25 19:49 UTC
Hi, I'm new here and still trying to learn things. I have been trying to display map but failed to do so with no error message. 

Here's what I've tried

map.component.ts

```
  mapChart: any = {};
  private readonly chartPackage = getPackageForChart(ChartType.Map);
  @ViewChild('containerEl', { read: ElementRef })
  private containerEl: ElementRef<HTMLElement>;

  constructor(private loaderService: ScriptLoaderService
            ) { }

  ngAfterViewInit(): void {
    this.loaderService.loadChartPackages(this.chartPackage).subscribe(() => {
          const data = google.visualization.arrayToDataTable(data);
          const options = {};
          this.mapChart = new google.visualization.Map(this.containerEl.nativeElement);
          this.mapChart.draw(data, options);
    });
  }
```

map.component.html
`<google-chart #containerEl></google-chart>`

app.module.ts
```
    imports: [
        ...,
        GoogleChartsModule.forRoot({
            mapsApiKey: <g-api-key>
        })
    ],
```
I've tried this code with other charts like Pie and Bar charts and it works just fine, but when I changed the package and type to map its not showing anything without any error. I'm not sure if I'm missing some steps for Map.

This might be related to https://github.com/FERNman/angular-google-charts/issues/164, but I don't understand where he got `GoogleChartsSettings` object and how/where should I use `const MyGoogleChartsSettings`

Any help will be very appreciated.

**Comment by cyberbobjr** [comment] 2020-12-15 10:48
Hi,
this is my diagnose : it seems that the service  "ScriptLoaderService" need the GOOGLE_CHARTS_CONFIG token, which normally is provided by the GoogleChartsModule.forRoot({config}).

But (i don't know why) this token is NULL in the DI.

So, my workaround :

* I cloned the project 
* I integrated the source of the project in my app like a "normal" module
* I added this line in the static declaration of the module :

```
export class GoogleChartsModule {
    public static forRoot(config: GoogleChartsConfig = {}): ModuleWithProviders<GoogleChartsModule> {
        return {
            ngModule: GoogleChartsModule,
            providers: [
                ScriptLoaderService,
                {provide: GOOGLE_CHARTS_CONFIG, useValue: config}
            ]
        };
    }
}
```

With that way, the ScriptLoaderService can access to the DI GOOGLE_CHARTS_CONFIG token.

**Comment by FERNman** [comment] 2021-01-16 10:29
I will close this as a duplicate of #162. To me, it seems you did everything right, but as @cyberbobjr pointed out, the `GOOGLE_CHARTS_CONFIG` token is not provided. Let's track the progress on this in the other issue, I already have an idea for a potential solution.

**Closed by FERNman** 2021-01-16 10:29 UTC
Labels: question
